name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install flatpak builder
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install flatpak-builder elfutils -y
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: pip install setuptools==69.5.1
      - run: npm ci
      - run: npm run publish
      - name: Build macos arm
        if: matrix.os == 'macos-latest'
        run: npm run publish -- --arch="arm64"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
